version: "3"
services:
  web:
    build:
      context: ./
      dockerfile: ./assemble-web/web/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./assemble-web:/usr/src/app
    stdin_open: true
