
package com.stacktrace.yo.assemble.group.models

object Models {

  // Commands: Do this action (potentially harmful)
  sealed trait Command
  case object Clear extends Command
  case class Add(value: Double) extends Command
  case class Subtract(value: Double) extends Command
  case class Divide(value: Double) extends Command
  case class Multiply(value: Double) extends Command
  case object PrintResult extends Command
  case object GetResult extends Command

  // Marker trait for subclasses generated by Protobuf
  // The rest of the events are present in target/scala-2.*/src_managed/...
  // The Events are generated by ScalaPB from the models.proto file
  // Events: I have done this action (not harmful)
  trait Event

}
